# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11c0f118bd4809f75e0dae445d155bb5c8d25ec4cd9bbde3bb2c790dd5e3414aad9fd3b58b498f87284d743b42201489ac94ac3d1b5f8adf6ddd5fdc5b5d4e50

test:
  secret_key_base: 8efc1794e6088a41fe774276cb60a627be38a16e772e4330b885924ea209cae4912c53ba551424231c768c800c0a3876b53e10a60620698fe9e11c2254a78945

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
